version: "3.9"

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: 
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/4938130
      # CD_EXCLUDE_MODS:
      MEMORY: 4G
      VERSION: 1.20.1
      EULA: "TRUE"
    tty: true
    stdin_open: true
    volumes:
      # attach a directory relative to the directory containing this compose file
      - Z:\mcdata:/data
    restart: on-failure:3

