version: "3"

services:
  minecraft:
    build: .
    container_name: 1.21.1-fabric-server
    ports:
      - "25565:25565"
    volumes:
      - /root/data-de-servers/fabric-1.21.1:/minecraft_fabric_server_1.21.1
    environment:
      - MINECRAFT_RAM=24G
    restart: on-failure:3   
    tty: true
    stdin_open: true
