version: "3"

services:
  minecraft:
    build: .
    container_name: minecraft-fabric-server
    ports:
      - "25565:25565"
    volumes:
      # - ./data:/minecraft
      - ./root/data-de-servers/fabric-1.21:/minecraft_fabric_server_1.21
    environment:
      - MINECRAFT_RAM=24G
    restart: unless-stopped
    tty: true
    stdin_open: true

volumes:
  minecraft_data:
    driver: local
